### ISSUE TITLE
The default value of filename should be returned by the server either from header, or from url instead of an empty one

### ISSUE THREAD

**Issue by aanersc** [nansencenter/django-geo-spaas-processing#15]
Downloaded dataset should be named based on its entry_id for all cases.

For copernicus harvested file the header of the response of the download link provide the associated part named `'filename=' `for find the name of the dataset based on it. But for the osisaf and other future download links, the header of the response whould be something like:
![image](https://user-images.githubusercontent.com/62345618/96114923-844f7980-0ee6-11eb-8b74-b312b4e392d6.png)

So no information can be gained about the filename from such a header. Thus, this line
https://github.com/nansencenter/django-geo-spaas-processing/blob/7793104419a786111342e121fbaae111acb72d64/geospaas_processing/downloaders.py#L65
should be corrected for solving this issue.

**Comment by akorosov** [comment]
Rather the filename should be returned by the server either from header, or from url.
